### ISSUE TITLE
Add support for EnumSet

### ISSUE THREAD

**Issue by mjureczko** [ocadotechnology/test-arranger#52]
Currently instantiation of EnumSet ends up with:
```
Caused by: java.lang.InstantiationError: java.util.EnumSet
	at java.base/jdk.internal.reflect.GeneratedSerializationConstructorAccessor6.newInstance(Unknown Source)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at org.objenesis.instantiator.sun.SunReflectionFactoryInstantiator.newInstance(SunReflectionFactoryInstantiator.java:48)
	at org.objenesis.ObjenesisBase.newInstance(ObjenesisBase.java:73)
	at org.jeasy.random.util.ReflectionUtils.createEmptyCollectionForType(ReflectionUtils.java:498)
	at org.jeasy.random.CollectionPopulator.getRandomCollection(CollectionPopulator.java:58)
	at org.jeasy.random.FieldPopulator.generateRandomValue(FieldPopulator.java:139)
	at org.jeasy.random.FieldPopulator.populateField(FieldPopulator.java:93)
	at org.jeasy.random.EasyRandom.populateField(EasyRandom.java:209)
	at org.jeasy.random.EasyRandom.populateFields(EasyRandom.java:198)
	at org.jeasy.random.EasyRandom.doPopulateBean(EasyRandom.java:165)
```

**Comment by mjureczko** [comment]
A related issue: https://github.com/j-easy/easy-random/issues/489
